# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-02 02:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import arhivator.logic.person
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(help_text='Tvoje ime', max_length=20, verbose_name='ime')),
                ('priimek', models.CharField(help_text='Tvoj priimek', max_length=20, verbose_name='priimek')),
                ('datum_rojstva', models.CharField(help_text='Tvoj datum rojstva', max_length=10, verbose_name='datum_rojstva')),
                ('EMSO', models.CharField(max_length=255, verbose_name='EMSO')),
            ],
        )
        # migrations.RunPython(add_social_apps, lambda apps, schema_editor: None),
        # migrations.RunPython(add_countries, lambda apps, schema_editor: None),
        # migrations.RunPython(add_languages, lambda apps, schema_editor: None),
    ]
